-- Client profile additions: a photo (same base64-data-URL approach as
-- profiles.photo for team members) and discrete, pinnable/timestamped notes
-- (client_notes) replacing the single clients.notes text blob — mirrors how
-- deal_notes already replaced deals.notes.
-- Run this once in the Supabase SQL editor for this project.

alter table clients
  add column if not exists photo text;

create table if not exists client_notes (
  id bigint generated by default as identity primary key,
  client_id bigint not null,
  text text not null,
  created_by text,
  pinned boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists client_notes_client_id_idx on client_notes (client_id);

alter table client_notes enable row level security;

drop policy if exists "client_notes_select" on client_notes;
create policy "client_notes_select" on client_notes for select using (true);

drop policy if exists "client_notes_insert" on client_notes;
create policy "client_notes_insert" on client_notes for insert with check (auth.role() = 'authenticated');

drop policy if exists "client_notes_update" on client_notes;
create policy "client_notes_update" on client_notes for update using (auth.role() = 'authenticated');

drop policy if exists "client_notes_delete" on client_notes;
create policy "client_notes_delete" on client_notes for delete using (auth.role() = 'authenticated');
